// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMf1XIDmiJIwtsA2i48nRBp8e-itM2PEg',
    appId: '1:658125819028:web:4b06cf5867babb67a23881',
    messagingSenderId: '658125819028',
    projectId: 'novastore-3739b',
    authDomain: 'novastore-3739b.firebaseapp.com',
    storageBucket: 'novastore-3739b.firebasestorage.app',
    measurementId: 'G-CLDBN4LXGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM4Z_0YSDdDc3DbH6lk8ZWlYV5uHCzFRw',
    appId: '1:658125819028:android:0659c3b0ac7fd475a23881',
    messagingSenderId: '658125819028',
    projectId: 'novastore-3739b',
    storageBucket: 'novastore-3739b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIhUi-rTRpArOC1qxU1Td1T9--aQiC8MY',
    appId: '1:658125819028:ios:623b8b3609942be4a23881',
    messagingSenderId: '658125819028',
    projectId: 'novastore-3739b',
    storageBucket: 'novastore-3739b.firebasestorage.app',
    iosBundleId: 'com.example.newstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIhUi-rTRpArOC1qxU1Td1T9--aQiC8MY',
    appId: '1:658125819028:ios:623b8b3609942be4a23881',
    messagingSenderId: '658125819028',
    projectId: 'novastore-3739b',
    storageBucket: 'novastore-3739b.firebasestorage.app',
    iosBundleId: 'com.example.newstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMf1XIDmiJIwtsA2i48nRBp8e-itM2PEg',
    appId: '1:658125819028:web:50889ed99a55dbffa23881',
    messagingSenderId: '658125819028',
    projectId: 'novastore-3739b',
    authDomain: 'novastore-3739b.firebaseapp.com',
    storageBucket: 'novastore-3739b.firebasestorage.app',
    measurementId: 'G-LWKL2SFZCP',
  );
}
