import 'package:newstore/shared/domain/entities/product.dart';

class MockData {
  static const List<Product> flashDeals = [
    Product(
      id: '1',
      name: 'Sculptural Chronos A1',
      brand: 'Horology House',
      price: 850.00,
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600',
      description: 'The Sculptural Chronos A1 isn\'t just a timepiece; it\'s a statement of architectural precision. Carved from high-density ceramic, its seamless casing flows into a bespoke integrated bracelet. Featuring a Swiss-made automatic movement with a 48-hour power reserve, this limited edition series merges historical craftsmanship with avant-garde aesthetics.',
      category: 'Luxury',
      stock: 12,
    ),
    Product(
      id: '2',
      name: 'Sonic-X Over-Ear',
      brand: 'Audio King',
      price: 299.00,
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=600',
      description: 'Premium sound experience with active noise cancellation and spatial audio technology.',
      category: 'Electronics',
      stock: 45,
    ),
    Product(
      id: '3',
      name: 'Eclipse Gold Frames',
      brand: 'Lumina',
      price: 180.00,
      imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=600',
      description: 'Elegant gold-rimmed frames designed for both style and durability.',
      category: 'Accessories',
      stock: 28,
    ),
  ];

  static const List<Product> recommended = [
    Product(
      id: '4',
      name: 'Air Zoom Velocity',
      brand: 'Nike Performance',
      price: 185.00,
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=600',
      description: 'Highly responsive cushioning for the serious runner.',
      category: 'Sports',
      stock: 20,
    ),
    Product(
      id: '5',
      name: 'Artisan Desert Boot',
      brand: 'Heritage Goods',
      price: 240.00,
      imageUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&q=80&w=600',
      description: 'Hand-crafted desert boots made with the finest suede.',
      category: 'Fashion',
      stock: 15,
    ),
    Product(
      id: '6',
      name: 'Oxford Linen Shirt',
      brand: 'The Essentials',
      price: 95.00,
      imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87034a264c1?auto=format&fit=crop&q=80&w=600',
      description: 'Breathable linen shirt perfect for the autumn collection.',
      category: 'Fashion',
      stock: 30,
    ),
    Product(
      id: '7',
      name: 'Lunar Studs Silver',
      brand: 'Aurora Fine',
      price: 420.00,
      imageUrl: 'https://images.unsplash.com/photo-1535633302703-b0703af46f32?auto=format&fit=crop&q=80&w=600',
      description: 'Sterling silver studs that capture the essence of moonlight.',
      category: 'Jewelry',
      stock: 10,
    ),
    Product(
      id: '8',
      name: 'The Heritage Runner',
      brand: 'Classic Sport',
      price: 420.00,
      imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=600',
      description: 'A modern take on the classic athletic runner.',
      category: 'Sports',
      stock: 24,
    ),
    Product(
      id: '9',
      name: 'Arch High-Top',
      brand: 'Street Flow',
      price: 385.00,
      imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=600',
      description: 'Premium high-top sneakers with intentional asymmetry.',
      category: 'Fashion',
      stock: 18,
    ),
    Product(
      id: '10',
      name: 'Ignite Racer',
      brand: 'Nova Performance',
      price: 290.00,
      imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&q=80&w=600',
      description: 'Engineered for speed and agility.',
      category: 'Sports',
      stock: 32,
    ),
    Product(
      id: '11',
      name: 'Classic Derby',
      brand: 'Tradition',
      price: 195.00,
      imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=600',
      description: 'Timeless footwear for formal and semi-formal occasions.',
      category: 'Fashion',
      stock: 12,
    ),
    Product(
      id: '12',
      name: 'Shadow Lite 2.0',
      brand: 'Stealth',
      price: 215.00,
      imageUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=600',
      description: 'Ultralight footwear for the urban explorer.',
      category: 'Fashion',
      stock: 40,
    ),
    Product(
      id: '13',
      name: 'Silver Bullet',
      brand: 'Prestige',
      price: 550.00,
      imageUrl: 'https://images.unsplash.com/photo-1511499767390-903390e62bc0?auto=format&fit=crop&q=80&w=600',
      description: 'Our most exclusive premium item in the collection.',
      category: 'Luxury',
      stock: 5,
    ),
  ];

  static const List<String> recentSearches = [
    'Luxury Watches',
    'Wireless Earbuds',
    'Leather Boots',
    'Silk Scarves',
  ];

  static const List<Map<String, dynamic>> orderHistory = [
    {
      'id': 'ORD-2024-001',
      'date': 'Oct 12, 2024',
      'status': 'Delivered',
      'total': 450.00,
      'items': 3,
    },
    {
      'id': 'ORD-2024-005',
      'date': 'Oct 15, 2024',
      'status': 'In Transit',
      'total': 120.00,
      'items': 1,
    },
  ];
}
